// The preload surface shares payload types with main registration. Results remain
// unknown until a renderer boundary parses them; this file has no runtime imports.
import type { IpcPayloads } from './ipc-payloads';

interface InvokeChannels {
  readonly openProjectDialog: 'project:openDialog';
  readonly openWslProjectDialog: 'project:openWslDialog';
  readonly newProjectDialog: 'project:newDialog';
  readonly scaffoldProject: 'project:scaffold';
  readonly createAstroProject: 'project:createAstro';
  readonly parentDialog: 'project:parentDialog';
  readonly createStarter: 'project:createStarter';
  readonly hasNodeModules: 'project:hasNodeModules';
  readonly installDeps: 'project:install';
  readonly scanProject: 'project:scan';
  readonly listProjectClasses: 'project:classes';
  readonly watchProject: 'watch:start';
  readonly listAssets: 'assets:list';
  readonly pickUploadAssets: 'assets:pickUpload';
  readonly uploadAssets: 'assets:upload';
  readonly moveAsset: 'assets:move';
  readonly renameAsset: 'assets:rename';
  readonly deleteAsset: 'assets:delete';
  readonly mkdirAssets: 'assets:mkdir';
  readonly readAssetText: 'assets:readText';
  readonly writeAssetText: 'assets:writeText';
  readonly readSymbolSource: 'src:readSymbol';
  readonly resolveSourcePath: 'src:resolvePath';
  readonly assetDimensions: 'assets:dimensions';
  readonly readSourceText: 'src:readText';
  readonly writeSourceText: 'src:writeText';
  readonly copySelection: 'selection:copy';
  readonly listCms: 'cms:list';
  readonly readCms: 'cms:read';
  readonly writeCms: 'cms:write';
  readonly createCms: 'cms:create';
  readonly deleteCms: 'cms:delete';
  readonly cmsUsage: 'cms:usage';
  readonly cmsAssetRef: 'cms:assetRef';
  readonly resolveImport: 'project:resolveImport';
  readonly cmsMeta: 'cms:meta';
  readonly contentConfig: 'content:config';
  readonly cssVariables: 'css:variables';
  readonly setCssVariable: 'css:setVariable';
  readonly moveCssVariables: 'css:moveVariables';
  readonly addCssVariables: 'css:addVariables';
  readonly renameCssVariables: 'css:renameVariables';
  readonly setCssSectionTitle: 'css:setSectionTitle';
  readonly removeCssSection: 'css:removeSection';
  readonly addCssSection: 'css:addSection';
  readonly moveCssHeading: 'css:moveHeading';
  readonly contentCollections: 'content:collections';
  readonly contentEntries: 'content:entries';
  readonly writeContentEntry: 'content:writeEntry';
  readonly validateContentEntry: 'content:validate';
  readonly contentTargets: 'content:targets';
  readonly contentRenamePlan: 'content:renamePlan';
  readonly renameContentEntry: 'content:rename';
  readonly setCmsMeta: 'cms:setMeta';
  readonly listRecents: 'recents:list';
  readonly addRecent: 'recents:add';
  readonly removeRecent: 'recents:remove';
  readonly refreshThumb: 'recents:refreshThumb';
  readonly readPage: 'page:read';
  readonly parsePageSource: 'page:parse';
  readonly writePage: 'page:write';
  readonly writePageRaw: 'page:writeRaw';
  readonly createPage: 'page:create';
  readonly deletePage: 'page:delete';
  readonly movePage: 'page:move';
  readonly createPageFolder: 'pagefolder:create';
  readonly renamePageFolder: 'pagefolder:rename';
  readonly deletePageFolder: 'pagefolder:delete';
  readonly importPathFor: 'page:importPathFor';
  readonly rebaseImport: 'page:rebaseImport';
  readonly createComponent: 'component:create';
  readonly componentProperties: 'component:properties';
  readonly editComponentProperties: 'component:editProperties';
  readonly componentUsage: 'component:usage';
  readonly dynamicPaths: 'page:dynamicPaths';
  readonly injectedRoutes: 'project:injectedRoutes';
  readonly sampleEntry: 'content:sampleEntry';
  readonly startDevServer: 'dev:start';
  readonly stopDevServer: 'dev:stop';
  readonly diagnoseDev: 'dev:diagnose';
  readonly probeDevPage: 'dev:probe';
  readonly listStyleFiles: 'style:listFiles';
  readonly listAstroStyleFiles: 'style:listAstroStyles';
  readonly readStyleFile: 'style:readFile';
  readonly writeStyleFile: 'style:writeFile';
  readonly gitInfo: 'git:info';
  readonly ghStatus: 'git:ghStatus';
  readonly gitInit: 'git:init';
  readonly gitCheckout: 'git:checkout';
  readonly previewAtCommit: 'preview:atCommit';
  readonly previewStop: 'preview:stop';
  readonly gitLog: 'git:log';
  readonly gitCommitFiles: 'git:commitFiles';
  readonly gitAllFiles: 'git:allFiles';
  readonly gitStatus: 'git:status';
  readonly gitFileAt: 'git:fileAt';
  readonly gitWorktrees: 'git:worktrees';
  readonly gitPark: 'git:park';
  readonly gitUnpark: 'git:unpark';
  readonly gitMerge: 'git:merge';
  readonly gitResolveMerge: 'git:resolveMerge';
  readonly gitDeleteBranch: 'git:deleteBranch';
  readonly gitCommit: 'git:commit';
  readonly gitRestoreFile: 'git:restoreFile';
  readonly gitRestoreProject: 'git:restoreProject';
  readonly gitPush: 'git:push';
  readonly gitPublish: 'git:publish';
  readonly openExternal: 'shell:openExternal';
  readonly pendingProject: 'project:pending';
  readonly closeProject: 'project:close';
  readonly startTerminal: 'terminal:start';
  readonly resizeTerminal: 'terminal:resize';
  readonly closeTerminal: 'terminal:close';
  readonly settings: 'settings:get';
  readonly nativeCopy: 'native:copy';
  readonly nativePaste: 'native:paste';
  readonly nativeUndo: 'native:undo';
  readonly nativeRedo: 'native:redo';
}

type InvokeSurface = {
  readonly [Method in keyof InvokeChannels]: (
    ...args: undefined extends IpcPayloads[InvokeChannels[Method]]
      ? [payload?: IpcPayloads[InvokeChannels[Method]]]
      : [payload: IpcPayloads[InvokeChannels[Method]]]
  ) => Promise<unknown>;
};

export type PreloadBridge = InvokeSurface & {
  readonly platform: NodeJS.Platform;
  readonly getFilePath: (file: File) => string | null;
  readonly terminalInput: (id: string, data: string) => void;
  readonly terminalAck: (id: string, count: number) => void;
  readonly terminalClipboardImage: (bytes: Uint8Array, mime: string) => Promise<unknown>;
  readonly onAssetsChanged: (callback: () => void) => () => void;
  readonly onCssChanged: (callback: () => void) => () => void;
  readonly onCmsChanged: (callback: () => void) => () => void;
  readonly onPageMaybeChanged: (callback: (data: unknown) => void) => () => void;
  readonly onThumbUpdated: (callback: (data: unknown) => void) => () => void;
  readonly onTerminalData: (callback: (data: unknown) => void) => () => void;
  readonly onTerminalExit: (callback: (data: unknown) => void) => () => void;
  readonly onTerminalProcess: (callback: (data: unknown) => void) => () => void;
  readonly onDevLog: (callback: (data: unknown) => void) => () => void;
  readonly onDevExit: (callback: (data: unknown) => void) => () => void;
  readonly onProgress: (callback: (data: unknown) => void) => () => void;
  readonly onCreateLog: (callback: (data: unknown) => void) => () => void;
  readonly onFsChanged: (callback: (data: unknown) => void) => () => void;
  readonly onMenu: (channel: string, callback: (data?: unknown) => void) => () => void;
};
